name: Build Solution and Generate Artifacts on Pull Request
 
on:

  pull_request:

    branches:

      - main  # Adjust to the target branch you want to monitor
 
jobs:

  build-solution-and-generate-artifacts:

    runs-on: windows-latest  # Use a Windows environment for .NET builds
 
    steps:

      # Checkout the repository code

      - name: Checkout Code

        uses: actions/checkout@v3
 
      - name: Install Build Tools

        run: |

          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.WebBuildTools --quiet --norestart" -y

          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
 
      # Setup .NET SDK

      - name: Setup .NET

        uses: actions/setup-dotnet@v3

        with:

          dotnet-version: '6.0'  # Use .NET 6
 
      # Restore dependencies for the entire solution

      - name: Restore Dependencies

        run: dotnet restore myopsapp.sln
 
      # Build the entire solution

      - name: Build Solution

        run: dotnet build myopsapp.sln --configuration Release --verbosity detailed
 
     
